services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dbt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbt
    environment:
      DBT_USER: admin
      DBT_PASSWORD: password
      DBT_HOST: postgres
      DBT_PORT: 5432
      DBT_DATABASE: my_database
      DBT_SCHEMA: public
      PREFECT_API_URL: "http://prefect-server:4200/api"
    volumes:
      - ./dbt:/usr/app/dbt
      - ./app:/usr/app
    depends_on:
      - postgres
      - prefect-server

  prefect-server:
    build:
      context: .
      dockerfile: Dockerfile.prefect
    container_name: prefect-server
    ports:
      - "4201:4200"
    depends_on:
      - postgres

volumes:
  postgres_data:
